In [1]:
import numpy as np
import scipy
import matplotlib.pyplot as plt

In [9]:
#define the pauli matrices
identity = np.array([[1,0],
                  [0,1]])

pauliX = np.array([[0,1],
                  [1,0]])

pauliY = np.array([[0,-1j],
                  [1j,0]])

pauliZ = np.array([[1,0],
                  [0,-1]])

# Trial 1 Calculation

In [23]:
#photon count data for trial 1
cH1 = 461
cV1 = 7.333333
cPlus1 = 222
cMinus1 = 220.333333
cRight1 = 228.666667
cLeft1 = 193.333333

#QST data for trial 1
aX1 = 0.003752
aY1 = 0.079540
aZ1 = 1.021261

#density matrix calculation
trial1Matrix = 1/2*(identity + aX1*pauliX + aY1*pauliY + aZ1*pauliZ)
print("The density matrix and trace are")
print(trial1Matrix)
print(np.trace(trial1Matrix))
print()

#stoke vector calculation
s0 = cH1 + cV1
s1 = cPlus1 - cMinus1
s2 = cRight1 - cLeft1
s3 = cH1 - cV1
stokeVector1 = np.array([s0,s1,s2,s3])

print("The Stoke vector is:")
print(stokeVector1)
print()


#bloch sphere vector calculation
blochVector1 = 1/s0*np.array([s1,s2,s3])
print("The Bloch sphere vector is:")
print(blochVector1)

The density matrix and trace are
[[ 1.0106305+0.j       0.001876 -0.03977j]
 [ 0.001876 +0.03977j -0.0106305+0.j     ]]
(1+0j)

The Stoke vector is:
[468.333333   1.666667  35.333334 453.666667]

The Bloch sphere vector is:
[0.00355872 0.07544484 0.96868328]


# Trial 2 Calculations

In [25]:
#photon count data for trial 2
cH2 = 11
cV2 = 387.666667
cPlus2 = 222.333333
cMinus2 = 241
cRight2 = 212
cLeft2 = 205.333333

#QST data for trial 2
aX2 = -0.43773
aY2 = 0.015633
aZ2 = -0.883273

#density matrix calculation
trial2Matrix = 1/2*(identity + aX2*pauliX + aY2*pauliY + aZ2*pauliZ)
print(trial2Matrix)
print(np.trace(trial2Matrix))
print()

#stoke vector calculation
s0 = cH2 + cV2
s1 = cPlus2 - cMinus2
s2 = cRight2 - cLeft2
s3 = cH2 - cV2
stokeVector2 = np.array([s0,s1,s2,s3])

print("The Stoke vector is:")
print(stokeVector2)
print()


#bloch sphere vector calculation
blochVector2 = 1/s0*np.array([s1,s2,s3])
print("The Bloch sphere vector is:")
print(blochVector2)

[[ 0.0583635+0.j        -0.218865 -0.0078165j]
 [-0.218865 +0.0078165j  0.9416365+0.j       ]]
(1+0j)

The Stoke vector is:
[ 398.666667  -18.666667    6.666667 -376.666667]

The Bloch sphere vector is:
[-0.04682274  0.01672241 -0.94481605]


# Trial 3 Calculations

In [26]:
#photon count data for trial 3
cH3 = 242.666667
cV3 = 206.666667
cPlus3 = 415.333333
cMinus3 = 9.666667
cRight3 = 257.666667
cLeft3 = 173.666667

#QST data for trial 3
aX3 = 0.932091
aY3 = 0.193005
aZ3 = 0.082716

trial3Matrix = 1/2*(identity + aX3*pauliX + aY3*pauliY + aZ3*pauliZ)
print(trial3Matrix)
print(np.trace(trial3Matrix))
print()

#stoke vector calculation
s0 = cH3 + cV3
s1 = cPlus3 - cMinus3
s2 = cRight3 - cLeft3
s3 = cH3 - cV3
stokeVector3 = np.array([s0,s1,s2,s3])

print("The Stoke vector is:")
print(stokeVector3)
print()


#bloch sphere vector calculation
blochVector3 = 1/s0*np.array([s1,s2,s3])
print("The Bloch sphere vector is:")
print(blochVector3)

[[0.541358 +0.j        0.4660455-0.0965025j]
 [0.4660455+0.0965025j 0.458642 +0.j       ]]
(1+0j)

The Stoke vector is:
[449.333334 405.666666  84.        36.      ]

The Bloch sphere vector is:
[0.90281899 0.18694362 0.08011869]


# Trial 4 Calculations

In [27]:
#photon count data for trial 4
cH4 = 226.666667
cV4 = 187
cPlus4 = 9.333333
cMinus4 = 413.333333
cRight4 = 192.666667
cLeft4 = 238.333333

#QST data for trial 4
aX4 = -0.956339
aY4 = -0.10801
aZ4 = 0.093898

#density matrix calculation
trial4Matrix = 1/2*(identity + aX4*pauliX + aY4*pauliY + aZ4*pauliZ)
print(trial4Matrix)
print(np.trace(trial4Matrix))
print()

#stoke vector calculation
s0 = cH4 + cV4
s1 = cPlus4 - cMinus4
s2 = cRight4 - cLeft4
s3 = cH4 - cV4
stokeVector4 = np.array([s0,s1,s2,s3])

print("The Stoke vector is:")
print(stokeVector4)
print()


#bloch sphere vector calculation
blochVector4 = 1/s0*np.array([s1,s2,s3])
print("The Bloch sphere vector is:")
print(blochVector4)

[[ 0.546949 +0.j       -0.4781695+0.054005j]
 [-0.4781695-0.054005j  0.453051 +0.j      ]]
(1+0j)

The Stoke vector is:
[ 413.666667 -404.        -45.666666   39.666667]

The Bloch sphere vector is:
[-0.97663175 -0.11039484  0.09589041]


# Trial 5 Calculations

In [28]:
#photon count data for trial 5
cH5 = 205.666667
cV5 = 247.333333
cPlus5 = 217.333333
cMinus5 = 247.333333
cRight5 = 466
cLeft5 = 5.666667

#QST data for trial 5
aX5 = -0.064779
aY5 = 0.99402
aZ5 = 0.089971

#density matrix calculation
trial5Matrix = 1/2*(identity + aX5*pauliX + aY5*pauliY + aZ5*pauliZ)
print(trial5Matrix)
print(np.trace(trial5Matrix))
print()

#stoke vector calculation
s0 = cH5 + cV5
s1 = cPlus5 - cMinus5
s2 = cRight5 - cLeft5
s3 = cH5 - cV5
stokeVector5 = np.array([s0,s1,s2,s3])

print("The Stoke vector is:")
print(stokeVector5)
print()


#bloch sphere vector calculation
blochVector5 = 1/s0*np.array([s1,s2,s3])
print("The Bloch sphere vector is:")
print(blochVector5)

[[ 0.5449855+0.j      -0.0323895-0.49701j]
 [-0.0323895+0.49701j  0.4550145+0.j     ]]
(1+0j)

The Stoke vector is:
[453.       -30.       460.333333 -41.666666]

The Bloch sphere vector is:
[-0.06622517  1.01618837 -0.0919794 ]


# Trial 6 Calculations

In [30]:
#photon count data for trial 6
cH6 = 257
cV6 = 177.666667
cPlus6 = 266.333333
cMinus6 = 181.666667
cRight6 = 16
cLeft6 = 377.666667

#QST data for trial 6
aX6 = 0.199008
aY6 = -0.850091
aZ6 = 0.186472

#density matrix calculation
trial6Matrix = 1/2*(identity + aX6*pauliX + aY6*pauliY + aZ6*pauliZ)
print(trial6Matrix)
print(np.trace(trial6Matrix))
print()

#stoke vector calculation
s0 = cH6 + cV6
s1 = cPlus6 - cMinus6
s2 = cRight6 - cLeft6
s3 = cH6 - cV6
stokeVector6 = np.array([s0,s1,s2,s3])

print("The Stoke vector is:")
print(stokeVector6)
print()


#bloch sphere vector calculation
blochVector6 = 1/s0*np.array([s1,s2,s3])
print("The Bloch sphere vector is:")
print(blochVector6)

[[0.593236+0.j        0.099504+0.4250455j]
 [0.099504-0.4250455j 0.406764+0.j       ]]
(1+0j)

The Stoke vector is:
[ 434.666667   84.666666 -361.666667   79.333333]

The Bloch sphere vector is:
[ 0.19478527 -0.83205521  0.18251534]


# Trial 7 Calculations

In [31]:
#photon count data for trial 7
cH7 = 160.333333
cV7 = 102.333333
cPlus7 = 120.666667
cMinus7 = 129.333333
cRight7 = 134.333333
cLeft7 = 122.666667

#QST data for trial 7
aX7 = -0.033781
aY7 = 0.45474
aZ7 = 0.220672

#density matrix calculation
trial7Matrix = 1/2*(identity + aX7*pauliX + aY7*pauliY + aZ7*pauliZ)
print(trial7Matrix)
print(np.trace(trial7Matrix))
print()

#stoke vector calculation
s0 = cH7 + cV7
s1 = cPlus7 - cMinus7
s2 = cRight7 - cLeft7
s3 = cH7 - cV7
stokeVector7 = np.array([s0,s1,s2,s3])

print("The Stoke vector is:")
print(stokeVector7)
print()


#bloch sphere vector calculation
blochVector7 = 1/s0*np.array([s1,s2,s3])
print("The Bloch sphere vector is:")
print(blochVector7)

[[ 0.610336 +0.j      -0.0168905-0.22737j]
 [-0.0168905+0.22737j  0.389664 +0.j     ]]
(1+0j)

The Stoke vector is:
[262.666666  -8.666666  11.666666  58.      ]

The Bloch sphere vector is:
[-0.03299492  0.04441624  0.22081218]


# Summary of Results

In [33]:
# Trial 1:
print("Trial 1:")
print("The density matrix and trace are")
print(trial1Matrix)
print(np.trace(trial1Matrix))
print()
print("The Stoke vector is:")
print(stokeVector1)
print()
print("The Bloch sphere vector is:")
print(blochVector1)
print()
print()

# Trial 2:
print("Trial 2:")
print("The density matrix and trace are")
print(trial2Matrix)
print(np.trace(trial2Matrix))
print()
print("The Stoke vector is:")
print(stokeVector2)
print()
print("The Bloch sphere vector is:")
print(blochVector2)
print()
print()

# Trial 3:
print("Trial 3:")
print("The density matrix and trace are")
print(trial3Matrix)
print(np.trace(trial3Matrix))
print()
print("The Stoke vector is:")
print(stokeVector3)
print()
print("The Bloch sphere vector is:")
print(blochVector3)
print()
print()

# Trial 4:
print("Trial 4:")
print("The density matrix and trace are")
print(trial4Matrix)
print(np.trace(trial4Matrix))
print()
print("The Stoke vector is:")
print(stokeVector4)
print()
print("The Bloch sphere vector is:")
print(blochVector4)
print()
print()

# Trial 5:
print("Trial 5:")
print("The density matrix and trace are")
print(trial5Matrix)
print(np.trace(trial5Matrix))
print()
print("The Stoke vector is:")
print(stokeVector5)
print()
print("The Bloch sphere vector is:")
print(blochVector5)
print()
print()

# Trial 6:
print("Trial 6:")
print("The density matrix and trace are")
print(trial6Matrix)
print(np.trace(trial6Matrix))
print()
print("The Stoke vector is:")
print(stokeVector6)
print()
print("The Bloch sphere vector is:")
print(blochVector6)
print()
print()

# Trial 7:
print("Trial 7:")
print("The density matrix and trace are")
print(trial7Matrix)
print(np.trace(trial7Matrix))
print()
print("The Stoke vector is:")
print(stokeVector7)
print()
print("The Bloch sphere vector is:")
print(blochVector7)
print()
print()

Trial 1:
The density matrix and trace are
[[ 1.0106305+0.j       0.001876 -0.03977j]
 [ 0.001876 +0.03977j -0.0106305+0.j     ]]
(1+0j)

The Stoke vector is:
[468.333333   1.666667  35.333334 453.666667]

The Bloch sphere vector is:
[0.00355872 0.07544484 0.96868328]


Trial 2:
The density matrix and trace are
[[ 0.0583635+0.j        -0.218865 -0.0078165j]
 [-0.218865 +0.0078165j  0.9416365+0.j       ]]
(1+0j)

The Stoke vector is:
[ 398.666667  -18.666667    6.666667 -376.666667]

The Bloch sphere vector is:
[-0.04682274  0.01672241 -0.94481605]


Trial 3:
The density matrix and trace are
[[0.541358 +0.j        0.4660455-0.0965025j]
 [0.4660455+0.0965025j 0.458642 +0.j       ]]
(1+0j)

The Stoke vector is:
[449.333334 405.666666  84.        36.      ]

The Bloch sphere vector is:
[0.90281899 0.18694362 0.08011869]


Trial 4:
The density matrix and trace are
[[ 0.546949 +0.j       -0.4781695+0.054005j]
 [-0.4781695-0.054005j  0.453051 +0.j      ]]
(1+0j)

The Stoke vector is:
[ 413.666